import type { Fluid } from '../types';

export const FLUIDS: Fluid[] = [
    // Common
    { name: 'Agua (20°C)', density: 998.2, kinematicViscosity: 1.004 },
    { name: 'Agua (4°C)', density: 1000, kinematicViscosity: 1.568 },
    { name: 'Agua de mar (20°C)', density: 1025, kinematicViscosity: 1.07 },
    { name: 'Aire (20°C, 1 atm)', density: 1.204, kinematicViscosity: 15.11 },
    { name: 'Glicerina', density: 1261, kinematicViscosity: 1180 },
    { name: 'Miel', density: 1420, kinematicViscosity: 10000 },
    
    // Alcohols
    { name: 'Alcohol Etílico (Etanol)', density: 789, kinematicViscosity: 1.52 },
    { name: 'Alcohol Metílico (Metanol)', density: 792, kinematicViscosity: 0.75 },
    { name: 'Alcohol Isopropílico', density: 786, kinematicViscosity: 3.0 },
    { name: 'Etilenglicol', density: 1113, kinematicViscosity: 19.1 },
    { name: 'Propilenglicol', density: 1036, kinematicViscosity: 56.0 },

    // Oils (various)
    { name: 'Aceite de motor SAE 10W', density: 870, kinematicViscosity: 65 },
    { name: 'Aceite de motor SAE 30W', density: 891, kinematicViscosity: 200 },
    { name: 'Aceite de motor SAE 50W', density: 902, kinematicViscosity: 520 },
    { name: 'Aceite de ricino', density: 961, kinematicViscosity: 1020 },
    { name: 'Aceite de linaza', density: 930, kinematicViscosity: 30 },
    { name: 'Aceite de oliva', density: 918, kinematicViscosity: 84 },
    { name: 'Aceite de soja', density: 924, kinematicViscosity: 40.5 },
    { name: 'Aceite de girasol', density: 920, kinematicViscosity: 58 },
    { name: 'Aceite hidráulico (ISO 32)', density: 870, kinematicViscosity: 32 },
    { name: 'Aceite hidráulico (ISO 46)', density: 875, kinematicViscosity: 46 },
    { name: 'Aceite hidráulico (ISO 68)', density: 880, kinematicViscosity: 68 },
    { name: 'Aceite de transformador', density: 872, kinematicViscosity: 27 },

    // Fuels
    { name: 'Gasolina', density: 737, kinematicViscosity: 0.6 },
    { name: 'Diésel', density: 832, kinematicViscosity: 3.5 },
    { name: 'Queroseno', density: 810, kinematicViscosity: 2.1 },
    { name: 'Combustible para aviones (Jet A-1)', density: 804, kinematicViscosity: 8.0 },
    { name: 'Biodiésel', density: 880, kinematicViscosity: 4.5 },
    { name: 'Butano (líquido)', density: 601, kinematicViscosity: 0.2 },
    { name: 'Propano (líquido)', density: 580, kinematicViscosity: 0.18 },

    // Hydrocarbons
    { name: 'Benceno', density: 876, kinematicViscosity: 0.75 },
    { name: 'Tolueno', density: 867, kinematicViscosity: 0.67 },
    { name: 'Hexano', density: 655, kinematicViscosity: 0.47 },
    { name: 'Octano', density: 703, kinematicViscosity: 0.75 },
    { name: 'Ciclohexano', density: 779, kinematicViscosity: 1.26 },
    { name: 'Estireno', density: 909, kinematicViscosity: 0.83 },

    // Solvents
    { name: 'Acetona', density: 784, kinematicViscosity: 0.4 },
    { name: 'Tetracloruro de carbono', density: 1594, kinematicViscosity: 0.6 },
    { name: 'Cloroformo', density: 1489, kinematicViscosity: 0.38 },
    { name: 'Éter etílico', density: 713, kinematicViscosity: 0.32 },
    { name: 'Acetato de etilo', density: 902, kinematicViscosity: 0.5 },
    { name: 'Disulfuro de carbono', density: 1263, kinematicViscosity: 0.29 },
    
    // Refrigerants
    { name: 'Amoníaco (líquido, 20°C)', density: 608, kinematicViscosity: 0.25 },
    { name: 'R-134a (líquido, 20°C)', density: 1225, kinematicViscosity: 0.21 },
    { name: 'R-22 (líquido, 20°C)', density: 1210, kinematicViscosity: 0.2 },
    { name: 'R-410A (líquido, 20°C)', density: 1062, kinematicViscosity: 0.18 },

    // Acids
    { name: 'Ácido acético', density: 1049, kinematicViscosity: 1.17 },
    { name: 'Ácido nítrico (70%)', density: 1413, kinematicViscosity: 1.2 },
    { name: 'Ácido fosfórico (85%)', density: 1685, kinematicViscosity: 15 },
    { name: 'Ácido sulfúrico (98%)', density: 1830, kinematicViscosity: 13.5 },

    // Food & Beverage
    { name: 'Leche entera', density: 1030, kinematicViscosity: 2.12 },
    { name: 'Cerveza (5% alcohol)', density: 1008, kinematicViscosity: 1.1 },
    { name: 'Vino', density: 990, kinematicViscosity: 1.4 },
    { name: 'Jugo de naranja', density: 1045, kinematicViscosity: 1.5 },
    { name: 'Salsa de tomate (Ketchup)', density: 1150, kinematicViscosity: 500 }, // Non-newtonian, approximation
    { name: 'Vinagre', density: 1010, kinematicViscosity: 1.05 },
    
    // Molten Metals
    { name: 'Mercurio', density: 13534, kinematicViscosity: 0.11 },
    { name: 'Plomo (fundido)', density: 10660, kinematicViscosity: 0.24 },
    { name: 'Sodio (fundido)', density: 927, kinematicViscosity: 0.75 },
    
    // Gases (at 20°C, 1 atm)
    { name: 'Helio', density: 0.166, kinematicViscosity: 122.0 },
    { name: 'Hidrógeno', density: 0.083, kinematicViscosity: 108.0 },
    { name: 'Nitrógeno', density: 1.165, kinematicViscosity: 15.6 },
    { name: 'Oxígeno', density: 1.331, kinematicViscosity: 15.7 },
    { name: 'Dióxido de carbono', density: 1.842, kinematicViscosity: 8.3 },
    { name: 'Metano', density: 0.668, kinematicViscosity: 16.2 },

    // More Fluids...
    { name: 'Anilina', density: 1022, kinematicViscosity: 4.3 },
    { name: 'Bromo (líquido)', density: 3120, kinematicViscosity: 0.3 },
    { name: 'Formaldehído', density: 815, kinematicViscosity: 0.5 },
    { name: 'Fenol', density: 1070, kinematicViscosity: 10 },
    { name: 'Piridina', density: 982, kinematicViscosity: 0.96 },
    { name: 'Freón 12 (líquido)', density: 1327, kinematicViscosity: 0.2 },
    { name: 'Nafta', density: 750, kinematicViscosity: 0.7 },
    { name: 'Heptano', density: 684, kinematicViscosity: 0.6 },
    { name: 'Pentano', density: 626, kinematicViscosity: 0.38 },
    { name: 'Propanol', density: 803, kinematicViscosity: 2.76 },
    { name: 'Butanol', density: 810, kinematicViscosity: 3.6 },
    { name: 'Xileno', density: 864, kinematicViscosity: 0.8 },
    { name: 'Dowtherm A', density: 1060, kinematicViscosity: 4.1 },
    { name: 'Tricloroetileno', density: 1460, kinematicViscosity: 0.39 },
    { name: 'Percloroetileno', density: 1623, kinematicViscosity: 0.54 },
    { name: 'Sangre (37°C)', density: 1060, kinematicViscosity: 3.5 },
    { name: 'Jarabe de maíz', density: 1380, kinematicViscosity: 1500 },
    { name: 'Líquido de frenos DOT 3', density: 1040, kinematicViscosity: 20 },
    { name: 'Líquido de transmisión (ATF)', density: 846, kinematicViscosity: 35 },
    { name: 'Creosota', density: 1070, kinematicViscosity: 4.0 },
    { name: 'Decano', density: 730, kinematicViscosity: 1.3 },
    { name: 'Acetaldehído', density: 788, kinematicViscosity: 0.3 },
    { name: 'Ácido fórmico', density: 1220, kinematicViscosity: 1.45 },
    { name: 'Furfurol', density: 1160, kinematicViscosity: 1.4 },
    { name: 'Nitrobenzeno', density: 1200, kinematicViscosity: 1.6 },
    { name: 'Nonano', density: 718, kinematicViscosity: 1.0 },
    { name: 'Ácido oleico', density: 895, kinematicViscosity: 28 },
    { name: 'Ácido propiónico', density: 990, kinematicViscosity: 1.1 },
    { name: 'Trementina', density: 870, kinematicViscosity: 1.7 },
    { name: 'Undecano', density: 740, kinematicViscosity: 1.7 },
    { name: 'Dodecano', density: 750, kinematicViscosity: 2.1 },
    { name: 'Tetradecano', density: 765, kinematicViscosity: 3.0 },
    { name: 'Hexadecano', density: 773, kinematicViscosity: 4.3 },
    { name: 'Ciclohexanol', density: 962, kinematicViscosity: 68 },
    { name: 'Dietilamina', density: 707, kinematicViscosity: 0.5 },
    { name: 'Dimetilformamida (DMF)', density: 944, kinematicViscosity: 0.98 },
    { name: 'Dimetilsulfóxido (DMSO)', density: 1100, kinematicViscosity: 2.0 },
    { name: 'Dioxano', density: 1034, kinematicViscosity: 1.2 },
    { name: 'Formamida', density: 1133, kinematicViscosity: 3.3 },
    { name: 'Hexafluorobenceno', density: 1610, kinematicViscosity: 0.6 },
    { name: 'Yodobenceno', density: 1830, kinematicViscosity: 1.0 },
    { name: 'Isobutanol', density: 802, kinematicViscosity: 4.9 },
    { name: 'Isooctano', density: 692, kinematicViscosity: 0.73 },
    { name: 'Ácido láctico', density: 1206, kinematicViscosity: 35 },
    { name: 'Ácido butírico', density: 960, kinematicViscosity: 1.6 },
    { name: 'Bromobenceno', density: 1495, kinematicViscosity: 0.75 },
    { name: 'Clorobenceno', density: 1106, kinematicViscosity: 0.72 },
    { name: 'Clorotolueno', density: 1080, kinematicViscosity: 0.8 },
    { name: 'Dibromoetano', density: 2180, kinematicViscosity: 0.8 },
    { name: 'Diclorobenceno', density: 1300, kinematicViscosity: 1.0 },
    { name: 'Dicloroetano', density: 1253, kinematicViscosity: 0.63 },
    { name: 'Diclorometano', density: 1326, kinematicViscosity: 0.33 },
    { name: 'Dietilenglicol', density: 1118, kinematicViscosity: 35.7 },
    { name: 'Trietilenglicol', density: 1126, kinematicViscosity: 47.7 },
    { name: 'Dipropilenglicol', density: 1023, kinematicViscosity: 107 },
    { name: 'Aceite de cacahuete', density: 915, kinematicViscosity: 65 },
    { name: 'Aceite de colza', density: 915, kinematicViscosity: 75 },
    { name: 'Aceite de sésamo', density: 923, kinematicViscosity: 55 },
    { name: 'Aceite de pescado', density: 925, kinematicViscosity: 40 },
    { name: 'Aceite de Tung', density: 938, kinematicViscosity: 250 },
    { name: 'Etilamina', density: 689, kinematicViscosity: 0.5 },
    { name: 'Etilbenceno', density: 867, kinematicViscosity: 0.75 },
    { name: 'Fluorobenceno', density: 1024, kinematicViscosity: 0.6 },
    { name: 'Glicerol', density: 1261, kinematicViscosity: 1180 },
    { name: 'Isobutano (líquido)', density: 551, kinematicViscosity: 0.2 },
    { name: 'Isopentano', density: 620, kinematicViscosity: 0.37 },
    { name: 'Limoneno', density: 841, kinematicViscosity: 1.1 },
    { name: 'Nitrometano', density: 1137, kinematicViscosity: 0.56 },
    { name: 'Octanol', density: 824, kinematicViscosity: 10.6 },
    { name: 'Pentanol', density: 814, kinematicViscosity: 4.4 },
    { name: 'Propilamina', density: 719, kinematicViscosity: 0.5 },
    { name: 'Propilbenceno', density: 862, kinematicViscosity: 0.8 },
    { name: 'Tetrahidrofurano (THF)', density: 889, kinematicViscosity: 0.54 },
    { name: 'Trietilamina', density: 728, kinematicViscosity: 0.5 },
    { name: 'Valeraldehído', density: 809, kinematicViscosity: 0.6 },
    { name: 'Ácido valérico', density: 940, kinematicViscosity: 2.2 },
    { name: 'Argón (líquido)', density: 1395, kinematicViscosity: 0.19 },
    { name: 'Neón (líquido)', density: 1207, kinematicViscosity: 0.1 },
    { name: 'Kriptón (líquido)', density: 2413, kinematicViscosity: 0.18 },
    { name: 'Xenón (líquido)', density: 2950, kinematicViscosity: 0.2 },
    { name: 'Flúor (líquido)', density: 1505, kinematicViscosity: 0.17 },
    { name: 'Cloro (líquido)', density: 1563, kinematicViscosity: 0.23 },
    { name: 'Dióxido de azufre (líquido)', density: 1460, kinematicViscosity: 0.27 },
    { name: 'Ácido clorhídrico (37%)', density: 1180, kinematicViscosity: 1.9 },
    { name: 'Hidróxido de sodio (50%)', density: 1525, kinematicViscosity: 70 },
    { name: 'Peróxido de hidrógeno (30%)', density: 1110, kinematicViscosity: 1.1 },
    { name: 'Ácido perclórico (70%)', density: 1670, kinematicViscosity: 2.5 },
    { name: 'Galio (líquido)', density: 6095, kinematicViscosity: 0.3 },
    { name: 'Cesio (líquido)', density: 1843, kinematicViscosity: 0.37 },
    { name: 'Rubidio (líquido)', density: 1470, kinematicViscosity: 0.46 },
    { name: 'Potasio (líquido)', density: 828, kinematicViscosity: 0.66 },
    { name: 'Litio (líquido)', density: 512, kinematicViscosity: 1.17 },
    { name: 'Bismuto (líquido)', density: 10050, kinematicViscosity: 0.16 },
    { name: 'Estaño (líquido)', density: 6980, kinematicViscosity: 0.28 },
    { name: 'Zinc (líquido)', density: 6570, kinematicViscosity: 0.55 },
    { name: 'Aluminio (líquido)', density: 2375, kinematicViscosity: 0.5 },
    { name: 'Plata (líquido)', density: 9320, kinematicViscosity: 0.28 },
    { name: 'Oro (líquido)', density: 17310, kinematicViscosity: 0.17 },
    { name: 'Cobre (líquido)', density: 8020, kinematicViscosity: 0.39 },
    { name: 'Hierro (líquido)', density: 6980, kinematicViscosity: 0.7 },
    { name: 'Níquel (líquido)', density: 7810, kinematicViscosity: 0.55 },
    { name: 'Titanio (líquido)', density: 4110, kinematicViscosity: 1.1 },
    { name: 'Agua pesada (D2O)', density: 1107, kinematicViscosity: 1.25 },
    { name: 'Óxido de etileno', density: 899, kinematicViscosity: 0.3 },
    { name: 'Óxido de propileno', density: 830, kinematicViscosity: 0.4 },
    { name: 'Anhídrido acético', density: 1082, kinematicViscosity: 0.83 },
    { name: 'Acrilonitrilo', density: 806, kinematicViscosity: 0.44 },
    { name: 'Cloruro de alilo', density: 938, kinematicViscosity: 0.38 },
    { name: 'Alcohol alílico', density: 854, kinematicViscosity: 1.5 },
    { name: 'Benzaldehído', density: 1044, kinematicViscosity: 1.3 },
    { name: 'Cloruro de bencilo', density: 1100, kinematicViscosity: 1.2 },
    { name: 'Alcohol bencílico', density: 1045, kinematicViscosity: 5.2 },
    { name: 'Cumeno', density: 862, kinematicViscosity: 0.88 },
    { name: 'Ciclohexanona', density: 948, kinematicViscosity: 2.3 },
    { name: 'Decalina', density: 880, kinematicViscosity: 2.5 },
    { name: 'Cloruro de etilo', density: 922, kinematicViscosity: 0.3 },
    { name: 'Yoduro de etilo', density: 1950, kinematicViscosity: 0.4 },
    { name: 'Propionaldehído', density: 807, kinematicViscosity: 0.4 },
    { name: 'Pirrolidina', density: 866, kinematicViscosity: 1.1 },
    { name: 'Tetralina', density: 970, kinematicViscosity: 2.2 },
].sort((a, b) => a.name.localeCompare(b.name));
